# Generated by Django 4.1.6 on 2024-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('cognom1', models.CharField(max_length=30)),
                ('cognom2', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('curs', models.CharField(max_length=30)),
                ('moduls', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=30)),
            ],
        ),
    ]
